// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iarpgwyskqucyzamevrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlhcnBnd3lza3F1Y3l6YW1ldnJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4MTk1NzMsImV4cCI6MjA2NDM5NTU3M30.Lp47SmDg0_t5CyGfazoNe3SJNHtw2V3ByLDT-YeNYqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);